import {
	Layers,
	BookOpen,
	Music,
	Headphones,
	Mic,
	Film,
	Tv,
	Globe,
	Map,
	FlaskConical,
	Atom,
	Landmark,
	Utensils,
	Coffee,
	Palette,
	Trophy,
	Dumbbell,
	Car,
	Plane,
	Ship,
	Cpu,
	Leaf,
	Heart,
	Star,
	Gamepad2,
	Calculator,
	Camera,
	Dog,
	Rocket,
	Flag,
} from 'lucide-svelte';

export const DECK_ICONS = [
	{ id: 'Layers', component: Layers },
	{ id: 'BookOpen', component: BookOpen },
	{ id: 'Music', component: Music },
	{ id: 'Headphones', component: Headphones },
	{ id: 'Mic', component: Mic },
	{ id: 'Film', component: Film },
	{ id: 'Tv', component: Tv },
	{ id: 'Globe', component: Globe },
	{ id: 'Map', component: Map },
	{ id: 'FlaskConical', component: FlaskConical },
	{ id: 'Atom', component: Atom },
	{ id: 'Landmark', component: Landmark },
	{ id: 'Utensils', component: Utensils },
	{ id: 'Coffee', component: Coffee },
	{ id: 'Palette', component: Palette },
	{ id: 'Trophy', component: Trophy },
	{ id: 'Dumbbell', component: Dumbbell },
	{ id: 'Car', component: Car },
	{ id: 'Plane', component: Plane },
	{ id: 'Ship', component: Ship },
	{ id: 'Cpu', component: Cpu },
	{ id: 'Leaf', component: Leaf },
	{ id: 'Heart', component: Heart },
	{ id: 'Star', component: Star },
	{ id: 'Gamepad2', component: Gamepad2 },
	{ id: 'Calculator', component: Calculator },
	{ id: 'Camera', component: Camera },
	{ id: 'Dog', component: Dog },
	{ id: 'Rocket', component: Rocket },
	{ id: 'Flag', component: Flag },
];

/** @param {string|null|undefined} id */
export function getDeckIconComponent(id) {
	return DECK_ICONS.find((i) => i.id === id)?.component ?? Layers;
}
